[font]
normal = { family = "Cozette", style = "Regular" }
bold = {family = "Cozette", style = "Regular"} # cozette's bold is not the same width as normal, so this.
builtin_box_drawing = false
size = 13.0
