"$schema" = 'https://starship.rs/config-schema.json'

format = """
[█](#7c7cef)\
$os\
$username$hostname\
[](bg:#d33893 fg:#7c7cef)\
$directory\
[ ](fg:#d33893 bg:#cd902c)\
$git_branch\
$git_status\
[ ](fg:#cd902c bg:#654199)\
$status\
[ ](fg:#654199)\
"""

right_format = """
[](#7f75b4)\
$time\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#7c7cef"
style_root = "bg:#7c7cef"
format = '[$user@]($style)'
disabled = false

[hostname]
ssh_only = false
format = "[$hostname ]($style)"
style = "bg:#7c7cef"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#d33893"
format = "[ $path ]($style)"
truncation_length = 1
fish_style_pwd_dir_length = 1

[status]
disabled = false
style = "bg:#654199"
format = "[$symbol$status ]($style)"
symbol = "× "

[time]
disabled = false
time_format = "%F %X" # Hour:Minute Format
style = "#7f75b4"
format = '[ $time ]($style)'

[git_branch]
style = "bg:#cd902c"
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_status]
style = "bg:#cd902c"
format = "([$all_status$ahead_behind ]($style))"
